import { Sparkles } from "lucide-react";
import { GuxButton, GuxCard, GuxModal } from "genesys-spark-components-react";
import type { Suggestion } from "./suggestions.types";

interface Props {
  suggestion: Suggestion;
  currentDraftText: string;
  onAccept: () => void;
  onReject: () => void;
  onRegenerate: () => Promise<void>;
  isRegenerating?: boolean;
  regenerateError?: string | null;
}

export function SuggestionReviewModal({
  suggestion,
  currentDraftText,
  onAccept,
  onReject,
  onRegenerate,
  isRegenerating = false,
  regenerateError,
}: Props) {
  const hasExistingContent = currentDraftText.trim().length > 0;
  const canRegenerate = !isRegenerating;

  return (
    <GuxModal open size="large" onGuxdismiss={onReject}>
      <div slot="title" className="guxModalTitle">
        Review suggestion — {suggestion.tone} ({suggestion.confidence}% match)
      </div>

      <div slot="content">
        <div
          className={
            hasExistingContent ? "compare" : "compare compare--single"
          }
        >
          {hasExistingContent && (
            <GuxCard accent="bordered" className="compareCard">
              <div className="gux-heading-md-semibold gux-text-color-primary">
                Current draft
              </div>
              <div className="pane color-primary diffPane suggestionReviewPane">
                {currentDraftText}
              </div>
            </GuxCard>
          )}
          <GuxCard accent="bordered" className="compareCard">
            <div className="gux-heading-md-semibold gux-text-color-primary">
              Suggested reply
            </div>
            <div className="pane color-primary diffPane suggestionReviewPane">
              {suggestion.fullText}
            </div>
          </GuxCard>
        </div>

        {regenerateError && (
          <div className="diffRegenerateError" role="alert">
            {regenerateError}
          </div>
        )}

        <div className="diffDisclaimer">
          <Sparkles size={16} className="diffDisclaimerIcon" aria-hidden />
          <span>
            This content was generated by AI. Please review carefully before
            applying.
          </span>
        </div>
      </div>

      <div slot="end-align-buttons">
        <GuxButton
          accent="secondary"
          disabled={!canRegenerate}
          onClick={() => void onRegenerate()}
          title={isRegenerating ? "Regenerating…" : "Generate a new suggestion"}
        >
          {isRegenerating ? "Regenerating…" : "Regenerate"}
        </GuxButton>
        <GuxButton accent="secondary" onClick={onReject} disabled={isRegenerating}>
          Discard
        </GuxButton>
        <GuxButton accent="primary" onClick={onAccept} disabled={isRegenerating}>
          Accept
        </GuxButton>
      </div>
    </GuxModal>
  );
}
